### ISSUE TITLE
Compile the beginning of ink_env

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#104]
The beginning of https://github.com/formal-land/coq-of-rust/blob/main/CoqOfRust/ink/ink_env.v starts with:
```coq
(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

Module types.
  Module FromLittleEndian.
    Class Trait
        (Self : Set)
        {Bytes : Set}
        `{core.default.Default.Trait Bytes}
        `{core.convert.AsRef.Trait Bytes}
        `{core.convert.AsMut.Trait Bytes} :
        Set := {
      Bytes := Bytes;
      from_le_bytes : ImplSelf.Bytes -> (M Self);
    }.
```

Make it compile in Coq, probably plugging/adding the missing traits in the standard library.

**Comment by InfiniteEchoes** [comment]
My observations: 

The module being imported is `CoqOfRust.CoqOfRust`. For the `std` part that I have designed, all of them are under `CoqOfRust.std`, and auxiliary definitions are defined in `CoqOfRust.lib.lib`. So every modules under `std` wouls start with a line of `Require Import CoqOfRust.lib.lib.`.

`CoqOfRust.CoqOfRust` should have overlapped/outdated content with `CoqOfRust.lib.lib`, in the auxiliary definitions(one issue here is whether we can unite the `CoqOfRust.v` and `lib.v` together). Merely import this file would not import modules like `core` and `std`. I wonder if we might need lines like `Require core` or equivalent.

**Comment by dhilst** [comment]
Oh, so we have the Traits, I was about to add those, thanks! I'll look at how to integrate CoqOfRust, lib and std

**Comment by dhilst** [comment]
The #108 files should add the stdlib dependencies that were missing to compile the start of ink_env but there is more stuff to do yet.
