### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#157]
Currently, we are adding more and more options to the `cargo coq-of-rust` command. It would be simpler to group all of them in a JSON configuration file. The goal of this issue is to add such a configuration file, grouping all existing command-line options. There should still be one command-lind option to give the path to this configuration file.

**Comment by dhilst** [comment]
I started creating a configuration file in the #133

**Comment by clarus** [comment]
Done.
