### ISSUE TITLE
Default trait methods as axioms for libraries

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#166]
In https://github.com/formal-land/coq-of-rust/blob/main/CoqOfRust/ink/ink_storage_traits.v there is a translation:
```coq
  Global Instance Method_key `{H : State.Trait} `(Trait)
    : Notation.Dot "key" := {
    Notation.dot (self : ref Self) :=
      (Pure Self::["KEY"]
      : M (H := H) ink_primitives.key.Key);
  }.
```
with an explicit definition instead of an axiom as this is a library file. Make this definition an axiom.

**Comment by InfiniteEchoes** [comment]
Close as this issue is fixed in other PRs.
