### ISSUE TITLE
For `examples/traits_parms.v`: Relation between definitions and their instances

### ISSUE THREAD

**Issue by InfiniteEchoes** [formal-land/coq-of-rust#209]
# Background

The general organization of existing `traits_parms` code is as follows:
```coq
(* 1. Some Trait definitions... *)
Module Foo. (* ... *) End Foo. (* And so on...*)

(* 2. A definition of a struct that needs to refer to the traits *)
Module SomeOtherType. (* ... *) End SomeOtherType.

(* 3. Implementations between the structs and the traits *)
Module Impl_traits_parms_Foo_for_traits_parms_SomeOtherType.
(* ...*)
End Impl_traits_parms_Foo_for_traits_parms_SomeOtherType.
(* The Impl list goes on... *)
```

We now define a completely new struct that is other than the `SomeOtherType`.

```coq
Unset Primitive Projections.
Module Struct1.
  Record t : Set := { 
    entry_1 : traits_parms.SomeTrait.SomeType;
  }.
End Struct1.
Global Set Primitive Projections.
Definition Struct1 := Struct1.t.
```

This simple snippet can inserted between 2 and 3, or appended right at the end of the code. When doing so, the code has different result:
- If we insert the code before 3, the code won't compile.
- If we insert the code after 3, the code will compile. And this actually is a problem.

# Problem 1: Role of the Instances
The names of the implementation modules suggest that they serve as instance for specific trait towards specific struct. In our example, it is (eventually) `Impl_traits_parms_SomeTrait_for_traits_parms_SomeOtherType` realizing a instance of `impl SomeTrait for SomeOtherType` in Rust. Our newly defined `Struct1`, when being added to the end of the code, would not cause any errors, which is inconsistent with its behavior when being put into the middle of the code. I suspect if it means that `Struct1` can accidently utilize the instance above.

# Problem 2: Order between Impls and Definitions
In the original code of `traits_parms`, definitions of varied items(including the referring ones and the referred ones) come before the implementations. The above code snippet shows however, that in some way you have to put implementations *before the item definitions* in order to use the new item. Although it seems to be negligible in the example code, #185 turns out to be such a ordering problem that seems to suggest you putting the implementations before item definitions.

**Comment by clarus** [comment]
This issue should be fixed by https://github.com/formal-land/coq-of-rust/pull/472 as trait instances are implicit and resolved at proof time now.
