### ISSUE TITLE
Handle type parameters with default for structs

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#223]
In https://github.com/formal-land/ink/blob/master/crates/storage/src/lazy/mapping.rs the type:
```rs
pub struct Mapping<K, V: Packed, KeyType: StorageKey = AutoKey> {
    #[allow(clippy::type_complexity)]
    _marker: PhantomData<fn() -> (K, V, KeyType)>,
}
```
has a default type parameter for `KeyType`. The goal of this issue is to implement such default parameters, like it is done for the traits.

**Comment by InfiniteEchoes** [comment]
This issue is closed by #381 .
