### ISSUE TITLE
Translate dead_code.rs

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#28]
Translate the file https://github.com/formal-land/coq-of-rust/blob/main/examples-from-rust-book/attributes/dead_code.rs

**Comment by clarus** [comment]
Done

**Comment by klausnat** [comment]
My solution to this issue:

Functions, Modules, Structs can have an attribute to disable the compilers dead_code lint.

If piece of code was marked by #[allow(dead_code)] I suggest to add a comment on top of this piece of code, stating that this function (Struct, module) was ignored by the compiler and should not be verified. 

so `Coq` code should look like this:
https://github.com/formal-land/coq-of-rust/pull/47/commits/a7328a302452760f9e36daed1bb86f6aca201df5
