### ISSUE TITLE
Import examples from the "Rust by Examples" guide

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#3]
Import the examples from https://doc.rust-lang.org/rust-by-example/index.html To name the examples, follow the same structure as in the source of the book: https://github.com/rust-lang/rust-by-example

This issue depends on https://github.com/formal-land/coq-of-rust/issues/2 that should be done first.

**Comment by dphov** [comment]
#15 Progress track here

**Comment by dphov** [comment]
Resolved
