### ISSUE TITLE
Getters for type aliases

### ISSUE THREAD

**Issue by InfiniteEchoes** [formal-land/coq-of-rust#388]
The following code wouldn't compile in `./examples/custom_types/enums_type_aliases_v1.v`:

``` coq
Module VeryVerboseEnumOfThingsToDoWithNumbers.
  Inductive t : Set :=
  | Add
  | Subtract.
End VeryVerboseEnumOfThingsToDoWithNumbers.
Definition VeryVerboseEnumOfThingsToDoWithNumbers : Set :=
  VeryVerboseEnumOfThingsToDoWithNumbers.t.

Definition Operations : Set :=
  enums_type_aliases_v1.VeryVerboseEnumOfThingsToDoWithNumbers.

(* #[allow(dead_code)] - function was ignored by the compiler *)
Definition main `{H' : State.Trait} : M (H := H') unit :=
  let x := enums_type_aliases_v1.Operations::["Add"] in
  Pure tt.
```

The reason is that, we have not defined the getters to access the elements via `DoubleColon` for the `VeryVerboseEnumOfThingsToDoWithNumbers` enum type. The goal is to find the correct place to define them.

**Comment by clarus** [comment]
This should be fine now with the untyped mode in https://github.com/formal-land/coq-of-rust/pull/472
