### ISSUE TITLE
Wrongly parsed `_crate` 

### ISSUE THREAD

**Issue by InfiniteEchoes** [formal-land/coq-of-rust#43]
In the current Coq library as well as the translated code, some functions are associated with a crate named `_crate`. A typical example is the default `print` function appeared everywhere in the translated snippets. 

After investigation, the cause that generates `_crate` originates in `lib/src/path.rs`:

```rust
pub fn to_valid_coq_name(str: String) -> String {
    let str = str::replace(&str, "$", "_");
    let str = str::replace(&str, "{{root}}", "Root");
    str::replace(&str, "::", ".")
}
```

Which is easy to see that it would replace anything with a `$` sign into an underscore. We have to figure out a way to correctly translate the `$crate`.

Official reference for `$crate`: https://doc.rust-lang.org/reference/macros-by-example.html

**Comment by clarus** [comment]
We now have a different handling of the names, so either this issue got resolved or does not apply anymore.
