### ISSUE TITLE
Reorganize the Architecture of Coq Library

### ISSUE THREAD

**Issue by InfiniteEchoes** [formal-land/coq-of-rust#44]
This issue arises from [translating `parsing_a_string.rs`](https://github.com/formal-land/coq-of-rust/issues/33). The current Coq library is intended to organize every functions into a single file in the topological order. It turns out that there could be mutual references between functions, and Coq is not that flexible to support such reference. e.g. [std::result::Result::unwrap](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap) and [std::fmt::Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html).

We should reorganize the file such that it follows the architecture of Rust documentation, e.g. define the type/trait/enum first, and then define the functions associated with this type/trait/enum.

**Comment by clarus** [comment]
Closing as we now translate the whole `alloc` and `core` libraries.
