### ISSUE TITLE
Have automated re-ordering

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#460]
Automatically re-order the definitions, at least for those with an explicit dependency link. Indeed, Coq requires all definitions to be ordered while Rust accepts them in any order, even with mutual recursion.

**Comment by jmikedupont2** [comment]
yes that is needed

**Comment by jmikedupont2** [comment]
here are my thoughts, I am going to implement a modification to coq to extract out the error message and use tactics to generate dummy code or some kind of parameterized type so that we can leave them in the wrong order and resolve them when used in a lazy fashion.

**Comment by clarus** [comment]
OK! Having some ways to use the definitions in a lazy way seems to be the right approach to avoid loops. We are also working on the `coq-of-rust` side to introduce lazy definitions in the generated code.

**Comment by clarus** [comment]
Closed by https://github.com/formal-land/coq-of-rust/pull/472
