### ISSUE TITLE
[meta] Use the coq::Expression type to print expressions

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#478]
For now, most of the pretty printing of the expressions in https://github.com/formal-land/coq-of-rust/blob/main/lib/src/expression.rs is done using combinators from `render.rs`. We should instead use combinators from the `coq.rs` file, and replace `to_doc` functions by `to_coq` versions. Do the same for `top_level.rs` too, or all other area where we use `render.rs` instead of `coq.rs`.

The goal is to uniformize the code for the printing.

**Comment by InfiniteEchoes** [comment]
There're 3 places I think would be unable to remove the `render.rs` dependency:
- `path.rs`: `Path` is actually a more low-level type in that `coq::Expression::just_name` depends on it. So its `to_doc` cannot be rewritten with `coq`'s combinators.
- `thir_expression.rs` and `thir_pattern.rs`: the only dependency that they are relying on is `render::capitalize()`. Although this function doesn't involve any dependencies with the rest of the code, there doesn't seem to have a better place to place this function other than `render.rs`.
