### ISSUE TITLE
Use a stable version of Rust

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#503]
Currently, we are using a nighlty version of Rust as described in https://github.com/formal-land/coq-of-rust/blob/main/rust-toolchain

Instead: use a stable version of Rust (if this is possible when interacting with the Rust compiler API). This might require to change the code a bit as the Rust compiler API keeps evolving.

**Comment by InfiniteEchoes** [comment]
I believe that this is impossible:
- Rust stable version forbids all unstable features
- From the [official documentation](https://rustc-dev-guide.rust-lang.org/rustc-driver.html), `rustc_driver` is itself an unstable API as well as basically the "main function" to hack around with the Rust language.

**Comment by clarus** [comment]
OK, this is what I feared. After a check, even tools like `cargo clippy` are based on a nightly version of Rust. Closing this issue then.
