### ISSUE TITLE
Move - Simulations - Binary format - Bytecode type

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#566]
Write a simulation for the `Bytecode` type and its dependencies in https://github.com/move-language/move-sui/blob/main/crates/move-binary-format/src/file_format.rs

For the simulations, we will not write the `ToValue` and `ToTy` functions.

**Comment by InfiniteEchoes** [comment]
Since for now I still don't see necessity to simulate `impl` functions for this type, this issue should be safe to close.
