### ISSUE TITLE
Move - Simulations - Verifier - PartialVMError/Result types

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#569]
Write a simulation for the types:

- `PartialVMError`
- `PartialVMResult`

and their dependencies. These types are imported in https://github.com/move-language/move-sui/blob/main/crates/move-bytecode-verifier/src/type_safety.rs

**Comment by InfiniteEchoes** [comment]
For now, I think we don't have anything else to add to these structs, including the functions.
