### ISSUE TITLE
Env: translate the caller function

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#89]
Depends on https://github.com/formal-land/coq-of-rust/issues/90

In https://github.com/paritytech/ink/blob/2eba99ee445a4aee34d0919041388e7e727f7ed8/crates/env/src/api.rs there is the Rust code:
```rust
pub fn caller<E>() -> E::AccountId
where
    E: Environment,
{
    <EnvInstance as OnInstance>::on_instance(|instance| {
        TypedEnvBackend::caller::<E>(instance)
    })
}
```
that we (incorrectly) translate to:
```coq
Definition caller
    {E : Set}
    `{Environment.Trait E}
    (_ : unit)
    : M ImplE.AccountId :=
  OnInstance.on_instance (fun instance => TypedEnvBackend.caller instance).
```

We should:

- [ ] remove the `(_ : unit)` parameter
- [ ] translate `E::AccountId` correctly

**Comment by InfiniteEchoes** [comment]
`(_ : unit)` happens when there's no arguments for a function. Does it mean that we should set it to nil when there're no arguments?

**Comment by clarus** [comment]
> `(_ : unit)` happens when there're no arguments for a function. Does it mean that we should set it to nil when there're no arguments?

Yes, we should have an empty list of arguments when there are no arguments.

**Comment by clarus** [comment]
Not a priority anymore.
