### ISSUE TITLE
Env: translate the Environment trait

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#90]
In https://github.com/paritytech/ink/blob/2eba99ee445a4aee34d0919041388e7e727f7ed8/crates/env/src/types.rs there is the definition of the trait `Environment`:
```rust
pub trait Environment {
    /// The maximum number of supported event topics provided by the runtime.
    ///
    /// The value must match the maximum number of supported event topics of the used
    /// runtime.
    const MAX_EVENT_TOPICS: usize;

    /// The account id type.
    type AccountId: 'static
        + scale::Codec
        + CodecAsType
        + Clone
        + PartialEq
        + Eq
        + Ord
        + AsRef<[u8]>
        + AsMut<[u8]>;
        
...
```
It is translated for now as:
```coq
Module Environment.
  Class Trait (Self : Set) : Set := {
    MAX_EVENT_TOPICS : usize;
    AccountId : Set;

...
```
in https://github.com/formal-land/coq-of-rust/blob/main/CoqOfRust/ink/Env.v

Instead, we want to have types that are "synonym fields" (with `:=` instead of `:`), and all the types being given as parameters together with the type-class information:
```coq
Module Environment.
  Class Trait (Self : Set) {AccountId : Set}
      `{scale.Codec AccountId}
      `{CodecAsType AccountId}
      `{Clone AccountId}
      ...
      : Set := {
    MAX_EVENT_TOPICS : usize;
    AccountId := AccountId;

...
```

**Comment by dhilst** [comment]
The `inv_env.v` file after the #99 MR, the parameters 

![image](https://github.com/formal-land/coq-of-rust/assets/392820/8e8ca947-84a9-4036-9749-b353b3fd79a7)
