### ISSUE TITLE
Remove the Definition unit

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#95]
Understand where the:
```coq
Definition _ : unit := run (tt).
```
come from in the translation and remove them/translate them correctly, depending on the issue.

**Comment by dhilst** [comment]
I found this comment: 
![image](https://github.com/formal-land/coq-of-rust/assets/392820/1b59ecbc-46ea-41d9-9c25-f57bbebe2ac1)

Here: https://github.com/paritytech/ink/blob/4fbfa98b444425c5801392d1108d21986a97178c/crates/ink/codegen/src/lib.rs#L24
